// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package omdb is a generated GoMock package.
package omdb

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetMovie mocks base method.
func (m *MockService) GetMovie(filter Filter) (MovieInformation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMovie", filter)
	ret0, _ := ret[0].(MovieInformation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMovie indicates an expected call of GetMovie.
func (mr *MockServiceMockRecorder) GetMovie(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMovie", reflect.TypeOf((*MockService)(nil).GetMovie), filter)
}

// GetMovies mocks base method.
func (m *MockService) GetMovies(searchWord, pagination string) (Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMovies", searchWord, pagination)
	ret0, _ := ret[0].(Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMovies indicates an expected call of GetMovies.
func (mr *MockServiceMockRecorder) GetMovies(searchWord, pagination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMovies", reflect.TypeOf((*MockService)(nil).GetMovies), searchWord, pagination)
}
